Require DP Monitor image to be set

diff --git a/stable/dynamic-gateway-service/templates/statefulset.yaml b/stable/dynamic-gateway-service/templates/statefulset.yaml
--- a/stable/dynamic-gateway-service/templates/statefulset.yaml
+++ b/stable/dynamic-gateway-service/templates/statefulset.yaml
@@ -108,6 +108,7 @@ spec:
             - sh
             - -c
             - |
+{{- if and .Values.datapowerMonitor.image.repository .Values.datapowerMonitor.image.tag }}
               sh /init/scripts/init-dpm-check.sh
               cp -RL /init/config/* /drouter/config
 {{- if .Values.datapower.adminUserSecret }}
@@ -127,6 +128,11 @@ spec:
               find /drouter/ramdisk2/mnt -type d -exec chown 101:101 {} \;
 {{- end }}
               find /drouter/ramdisk2/mnt -type d -exec chmod 0777 {} \;
+{{- end }}
+{{- else }}
+              echo "ERROR: USER MUST SPECIFY A DATAPOWER MONITOR IMAGE"
+              echo "Please set datapowerMonitor.image.repository and datapowerMonitor.image.tag"
+              exit 1
 {{- end }}
           volumeMounts:
             - name: init-config-volume
